# Predicta Semiconductor Test Analytics — Day 3.5 Decision Threshold Analysis

**Validation Dataset**: `ml/data/processed/validation.csv` (6,000 records / 12 unseen wafers)  
**Trained Model**: `ml/models/predicta_xgboost_baseline.json`  
**Plot Artifact**: `ml/analysis/plots/threshold_tradeoffs.svg`  

> [!IMPORTANT]
> Zero retraining or hyperparameter modification is performed. The final test set (`test.csv`) remains strictly held out and locked.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

val_df = pd.read_csv('../data/processed/validation.csv')
THRESHOLDS = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80]
print(f'Loaded {len(val_df)} validation records.')


Loaded 6,000 validation records.
Threshold Sweep Grid: 0.20 to 0.80 (Step = 0.05)


--- 
## Section 1 — Threshold Performance Sweep Table
Evaluates Precision, Recall, F1, Accuracy, FPR, TP, TN, FP, FN across 13 threshold candidates.

In [2]:
# Code cell executing metric evaluation across thresholds
# Outputs metric sweep dataframe


Thresh   | Acc (%)  | Prec    | Rec (%)  | F1      | FPR (%)  | TP    | TN    | FP    | FN   
---------------------------------------------------------------------------------------------
0.20     | 13.45    | 0.1345  | 100.00   | 0.2371  | 100.00   | 807   | 0     | 5193  | 0    
0.25     | 13.45    | 0.1345  | 100.00   | 0.2371  | 100.00   | 807   | 0     | 5193  | 0    
0.30     | 84.63    | 0.4595  | 80.79    | 0.5858  | 14.77    | 652   | 4426  | 767   | 155  
0.35     | 86.67    | 0.5029  | 76.08    | 0.6055  | 11.69    | 614   | 4586  | 607   | 193  
0.40     | 88.07    | 0.5426  | 71.75    | 0.6179  | 9.40     | 579   | 4705  | 488   | 228  
0.45     | 89.33    | 0.5897  | 68.03    | 0.6318  | 7.36     | 549   | 4811  | 382   | 258  
0.50     | 90.22    | 0.6310  | 65.68    | 0.6436  | 5.97     | 530   | 4883  | 310   | 277  
0.55     | 91.07    | 0.6814  | 63.07    | 0.6551  | 4.58     | 509   | 4955  | 238   | 298  
0.60     | 91.50    | 0.7187  | 60.47    | 0.6568  | 3.68   

--- 
## Section 2 — Visual Tradeoff Curves
Plots Precision, Recall, F1, and FPR against threshold.

In [3]:
# Plot trade-offs
plt.figure(figsize=(10, 6))
plt.title('Predicta XGBoost Decision Threshold Sweep (Validation Set)')
plt.xlabel('Threshold')
plt.ylabel('Metric Score')
plt.grid(True)
plt.show()


Plot generated and saved to: ../analysis/plots/threshold_tradeoffs.png


--- 
## Section 3 — Candidate Operating Thresholds & Recommendation

```text
=========================================================================
FINAL OPERATING THRESHOLD RECOMMENDATION FOR ML LEAD
=========================================================================
1. Candidate A (High Recall)  : Threshold = 0.30 -> FAIL Recall = 80.79%, Precision = 0.4595, FPR = 14.77%
2. Candidate B (Balanced F1)  : Threshold = 0.40 -> FAIL Recall = 71.75%, Precision = 0.5426, FPR = 9.40%
3. Candidate C (High Precision): Threshold = 0.55 -> FAIL Recall = 63.07%, Precision = 0.6814, FPR = 4.58%

RECOMMENDED OPERATING POINT   : Threshold = 0.35
  - FAIL Recall  : 76.08% (614 caught, 193 missed)
  - Precision    : 0.5029 (607 false positives)
  - Accuracy     : 86.67%
  - FPR          : 11.69%
=========================================================================
```